import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "styles/Home.module.scss";
import Greeter from "../components/Greeter";
import Layout from "../components/Layout";
import { ConnectButton } from "@rainbow-me/rainbowkit";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Turborepo Web3 Starter Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            {/* Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code> */}
          </p>
          <ConnectButton />
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/turbo.svg"
            alt="Turborepo Logo"
            width={60}
            height={37}
            priority
          />
          <h1 className="mx-2 text-3xl font-semibold">
            Turborepo zkSync Starter Kit
          </h1>
        </div>

        <div className={styles.card}>
          <Greeter />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>⚡ Application</h2>
            <p>
              Next.js React app with Typescript, zkSync Web3 SDK, wagmi,
              RainbowKit, ethers.js
            </p>
          </a>
          <a
            href="https://era.zksync.io/docs/dev/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>⚡ Contracts</h2>
            <p>Hardhat with zkSync plugins and local L2 test network</p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>📦 Turborepo</h2>
            <p>Share configuration and dependencies, manage tasks</p>
          </a>
        </div>
      </main>
    </>
  );
};

export default Home;
